language: bash
sudo: required
services:
- docker
script:
- make test
notifications:
  slack:
    rooms:
      secure: D9HJPlUg/lfK356WvOcQWinu2cWKqHdG0CFJbnfP/0mh0V2cpFiBhOnvX4CO71ChjiFxpnTpiKyCNyYc+C9r6ddysi+aGHAl6HlbenvNrnRFZmh0Fsu6m6cZe9AStuAbFjGsginQ5xG2NUK8LPZxwNWo+aEC1Pnm6Cd2xjxosQXf/lAltveiOKv70inYiN36iyFkW3jZgO7aKU9n7RfZiWQolvQTGxLj6+U5Wc3sM6E6F0My5850RLkMIHm5tr9ZY7EbRZgNdYw4waYOtkeHg9t1+LJSidb41rRMQObsIVpv69s282ZhL8iD1v/gpaohakE5LG6QLley5dxHGsSTBQVn3ac4RnQWIF2yWya27mRvTNJDJ6lDYx0IaLeM3kVty2BSVVQEtzFJLO76lzmGp/6jhSXwP970TUeFlUyg3svN1N/AuKhy6+FgxtFJwEVJRXzceGsvaMFClBpWFXXFCEah2DYihXUFD4mtbeTotSm/ihIDR2VaoBQZhw34E0w9xh1Q1om7m+5sgBuKblun3zQX8Fvji/AdtkJxE5rDEVmX39fgR3VmzfjTcBkgIifeZCs6EtPvQ08Jn2HqeAUumSUlum1HbqciKZOHcDovRCu41jT5Iy8gQ7RWEVht42rJjn00dT4dAW+GvRTlAfBJ2hxKUPb3YgC158aWTFAlruc=
